version: '3.4'

services:
  minio:
    image: minio/minio
    hostname: minio1
    volumes:
      - minio-data:/export
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server export

volumes:
  minio-data:

